### ISSUE TITLE
[Python] [to_Pandas(),to_pydict()] ArrowException: Unknown error: Wrapping failed

### ISSUE THREAD

**Issue by Harshitg** [blue-yonder/turbodbc#271]
```
cursor.execute(query)
table = cursor.fetchallarrow()
df = table.to_pandas()
dict1 = table.to_pydict()
```

to_Pandas(), to_pydict() lead to below mentioned trackeback

to_Pandas()
```
  File "<ipython-input-78-33874de08f1b>", line 1, in <module>
    table.to_pandas()
  File "pyarrow\array.pxi", line 587, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow\table.pxi", line 1640, in pyarrow.lib.Table._to_pandas
  File "C:\Users\Python\Python37\site-packages\pyarrow\pandas_compat.py", line 766, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "C:\Users\HarshitGupta\AppData\Roaming\Python\Python37\site-packages\pyarrow\pandas_compat.py", line 1102, in _table_to_blocks
    list(extension_columns.keys()))
  File "pyarrow\table.pxi", line 1107, in pyarrow.lib.table_to_blocks
  File "pyarrow\error.pxi", line 117, in pyarrow.lib.check_status
ArrowException: Unknown error: Wrapping BLAH BLAH � �           failed
```

to_Pydict()

```
Traceback (most recent call last):
  File "<ipython-input-79-77cf4396cf20>", line 1, in <module>
    table.to_pydict()
  File "pyarrow\table.pxi", line 1662, in pyarrow.lib.Table.to_pydict
  File "pyarrow\table.pxi", line 453, in pyarrow.lib.ChunkedArray.to_pylist
  File "pyarrow\array.pxi", line 894, in __iter__
  File "pyarrow\scalar.pxi", line 532, in pyarrow.lib.StringValue.as_py
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 22: invalid start byte
```

This seems to be an encoding issue, while reading from the MSSQL database. Any idea if i can specify the necessary encoding parameter in turbodbc?

**Comment by wei-ann-Github** [comment]
@zacqed , you closed this issue that you opened. Did you manage to find a solution?
