### ISSUE TITLE
cannot import connect

### ISSUE THREAD

**Issue by SSASI74** [blue-yonder/turbodbc#311]
Hi all, 
I have finally managed to install.

when I run this line

from turbodbc import connect

however, I get the message cannot import connect

any ideas?

**Comment by xhochy** [comment]
Can you post the full traceback?

**Comment by SSASI74** [comment]
cannot import name 'connect'
Stack trace:
 >  File "C:\Users\Something\source\repos\Somethingelse\turbodbc.py", line 9, in <module> (Current frame)
 >    from turbodbc import connect
 >  File "C:\Users\Something\source\repos\Somethingelse\turbodbc.py", line 1, in <module>
 >    import turbodbc
Loaded 'turbodbc'
Loaded 'runpy'
cannot import name 'connect'
Stack trace:
 >  File "C:\Users\Something\source\repos\Somethingelse\turbodbc.py", line 9, in <module>
 >    from turbodbc import connect
 >  File "C:\Users\Something\source\repos\Somethingelse\turbodbc.py", line 1, in <module> (Current frame)
 >    import turbodbc
Traceback (most recent call last):
  File "C:\Users\Something\.conda\envs\Conda36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Something\.conda\envs\Conda36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\microsoft\python\core\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Users\Something\.conda\envs\Conda36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Something\.conda\envs\Conda36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Something\.conda\envs\Conda36\lib\runpy.py", line 85, in _run_code
The thread 'MainThread' (0x1) has exited with code 0 (0x0).
    exec(code, run_globals)
  File "C:\Users\Something\source\repos\Somethingelse\turbodbc.py", line 1, in <module>
    import turbodbc
  File "C:\Users\Something\source\repos\Somethingelse\turbodbc.py", line 9, in <module>
    from turbodbc import connect
ImportError: cannot import name 'connect'
The program 'python.exe' has exited with code -1 (0xffffffff).

**Comment by SSASI74** [comment]
thanks in advance

**Comment by xhochy** [comment]
You have named your Python module also `turbodbc` thus your code will try to import `connect` from it. Please rename `"C:\Users\Something\source\repos\Somethingelse\turbodbc.py"` to something else.

**Comment by SSASI74** [comment]
nice one,

schoolboy error
