### ISSUE TITLE
turbodbc.connect fails when pandas is also imported

### ISSUE THREAD

**Issue by connesy** [blue-yonder/turbodbc#320]
Environment:
OS: Ubuntu 20.04
MySQL odbc driver: MySQL ODBC 8.0 Unicode Driver
Python: 3.9.4
turbodbc: 4.2.1
Pandas: 1.3.2

The following works fine:
```python
# test_script.py
import turbodbc
connection_string = 'DRIVER={MySQL ODBC 8.0 Unicode Driver};HOST=<HOST>;PORT=<PORT>;DATABASE=<DATABASE>;UID=<UID>;PWD=<PWD>'
connection = turbodbc.connect(connection_string=connection_string)
print(connection)
```
```python
>>> python test_script.py
<turbodbc.connection.Connection object at 0x7f26b1076fd0>
```

But when I also import `pandas` in the same file, I get this error:
```python
# test_script.py
import turbodbc
import pandas
connection_string = 'DRIVER={MySQL ODBC 8.0 Unicode Driver};HOST=<HOST>;PORT=<PORT>;DATABASE=<DATABASE>;UID=<UID>;PWD=<PWD>'
connection = turbodbc.connect(connection_string=connection_string)
```
```python
>>> python test_script.py
Traceback (most recent call last):
  File "/home/python/miniconda3/envs/prod/lib/python3.9/site-packages/turbodbc/exceptions.py", line 41, in wrapper
    return f(*args, **kwds)
  File "/home/python/miniconda3/envs/prod/lib/python3.9/site-packages/turbodbc/connect.py", line 38, in connect
    connection = Connection(intern_connect(connection_string,
turbodbc_intern.Error: ODBC error
state: 01000
native error code: 0
message: [unixODBC][Driver Manager]Can't open lib '/usr/lib/x86_64-linux-gnu/odbc/libmyodbc8w.so' : file not found
```

I have also tried isolating the `turbodbc` code in its own module, but that also doesn't work:
```python
# library.py
import turbodbc
def get_connection():
    connection_string = 'DRIVER={MySQL ODBC 8.0 Unicode Driver};HOST=<HOST>;PORT=<PORT>;DATABASE=<DATABASE>;UID=<UID>;PWD=<PWD>'
    connection = turbodbc.connect(connection_string=connection_string)
    return connection
```
```python
# test_script.py
import library
import pandas  # Without this, it works fine
connection = library.get_connection()
print(connection)
```
```python
>>> python test_script.py
Traceback (most recent call last):
  File "/home/python/miniconda3/envs/prod/lib/python3.9/site-packages/turbodbc/exceptions.py", line 41, in wrapper
    return f(*args, **kwds)
  File "/home/python/miniconda3/envs/prod/lib/python3.9/site-packages/turbodbc/connect.py", line 38, in connect
    connection = Connection(intern_connect(connection_string,
turbodbc_intern.Error: ODBC error
state: 01000
native error code: 0
message: [unixODBC][Driver Manager]Can't open lib '/usr/lib/x86_64-linux-gnu/odbc/libmyodbc8w.so' : file not found
```

It also doesn't matter whether `pandas` is imported before or after `turbodbc`.

**Comment by connesy** [comment]
After looking more into this, it turned out to be an issue with the `libmysqlclient21` package as documented here: https://bugs.launchpad.net/ubuntu/+source/mysql-8.0/+bug/1889851

I will close this issue.
