### ISSUE TITLE
Minimal example of installing turbodbc and pyarrow without conda

### ISSUE THREAD

**Issue by ldacey** [blue-yonder/turbodbc#329]
I spent an obscene amount of time over the weekend trying to get turbodbc to recognize pyarrow when I install the libraries with pip (in the correct order).

Is it possible for someone to help me with a minimal working example? I know conda-forge is recommended (and it is what I am using right now), but I really want the ability to use pip instead because that is what some other major libraries I use support, and what some internal teams at work are using.

Trying to simply install turbodbc with pip never worked for me, so I assume I need to build it from source (I am not really familiar with how that works, so I was only able to modify some examples I saw). 

This is one of the examples I tried to make work with pyarrow == 5.0.0 and turbodbc == 4.2.1 (out of dozens of attempts, so there may have been better/closer examples).

```
RUN pip install --upgrade pip==${AIRFLOW_PIP_VERSION} \
    && pip install --no-cache-dir \
        cmake \
        wheel \
        pyarrow==5.0.0 \
    && git clone \
        --depth=1 \
        --branch 4.2.1 \
        https://github.com/blue-yonder/turbodbc.git \
        /turbodbc \
    && curl -o /tmp/pybind11.tar.gz -SL https://github.com/pybind/pybind11/archive/v2.6.2.tar.gz \
    && tar -xvf /tmp/pybind11.tar.gz -C /turbodbc --strip-components 1 \
    && mkdir -p /turbodbc/build \ 
    && cd /turbodbc/build \
    && cmake -GNinja \
      -DCMAKE_INSTALL_PREFIX=./dist \
      -DCMAKE_INSTALL_LIBDIR=lib \
      -DPYTHON_EXECUTABLE=/opt/venv/airflow/bin/python \
      /turbodbc \
    && ninja \
    && cd /turbodbc \
    && python setup.py build_ext --inplace \
    && python setup.py build_ext bdist_wheel \
    && pip install /turbodbc/dist/pybind11-2.6.2-py2.py3-none-any.whl turbodbc
```

I also tried using symlinks and running  `python -c "import pyarrow; pyarrow.create_library_symlinks()"`

The error generally was the Pyarrow was not installed, even though it was.

**Comment by alippai** [comment]
I don't have time to work on this, but I'd try `pip install --no-binary` for both pyarrow and turbodbc first to see how it compiles, what error messages it throws (you might need boost, unixodbc etc for successful build). https://github.com/conda-forge/turbodbc-feedstock/blob/master/recipe/meta.yaml#L29-L39 https://pip.pypa.io/en/latest/cli/pip_install/#install-no-binary

**Comment by alippai** [comment]
Make sure that the required packages like pip and setuptools are fresh as well.

**Comment by dhirschfeld** [comment]
> *what some internal teams at work are using.*

You can pip install into a conda environment which usually works perfectly fine for non-compiled dependencies so you may have better luck going that route.

**Comment by peter-wimsey** [comment]
I too have spent an inordinate amount of time on this install, first in 2019 #218 and then again last year without any success.

There might be some conda/pip combination that works but I have given up on pyarrow support in a pure pip install.

**Comment by ldacey** [comment]
Here is the Dockerfile I am working on for this. No luck yet so I will edit this comment if I get results. I am trying to install with the --no-binary:all argument. I added a few dependencies pyarrow needs to build from source to see if it will help.


```
FROM python:3.9-slim-buster
SHELL ["/bin/bash", "-o", "pipefail", "-e", "-u", "-x", "-c"]

ARG VIRTUAL_ENV=/opt/venv
ARG PYARROW_VERSION=5.0.0
ARG TURBODBC_VERSION=4.2.1

ENV VIRTUAL_ENV=${VIRTUAL_ENV} \
    TURBODBC_VERSION=${TURBODBC_VERSION} \
    PYARROW_VERSION=${PYARROW_VERSION} \
    DEBIAN_FRONTEND=noninteractive \
    LANGUAGE=C.UTF-8 \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    LC_CTYPE=C.UTF-8 \
    LC_MESSAGES=C.UTF-8

RUN apt-get update -y -q && \
    apt-get install -y -q --no-install-recommends \
    autoconf \
    bison \
    cmake \
    flex \
    gcc \
    git \
    g++ \
    libboost-all-dev \
    libjemalloc-dev \
    libsnappy-dev \
    ninja-build \
    python-pyodbc \
    python3-dev \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/* \
    && python -m venv ${VIRTUAL_ENV}

ENV PATH=${VIRTUAL_ENV}/bin:$PATH

WORKDIR ${VIRTUAL_ENV}

RUN pip install --upgrade pip==21.3.1 \
    && pip install --no-cache-dir \
    wheel \
    cmake \
    setuptools \
    numpy \
    pybind11 \
    pytest-cov \
    mock

RUN pip install --no-cache-dir pyarrow==${PYARROW_VERSION} --no-binary :all: \
    && pip install --no-cache-dir turbodbc==${TURBODBC_VERSION} --no-binary :all:
```

**Comment by ldacey** [comment]
Also, here is how I currently achieve having pyarrow and turbodbc installed without (technically) conda installed in my final image. I would still like the ability to be able to skip conda altogether though so I could use the official Airflow image as a base like my coworkers are using.

This stage uses mambaforge to create an environment from a conda-env.yml file which includes all of the libraries I need from conda-forge and some from pip. It then uses conda-pack (https://pythonspeed.com/articles/conda-docker-image-size/) to make a new directory with all of the installed packages.

```
FROM condaforge/mambaforge:latest as python-dependencies

ARG ENV_FILE=conda-env.yml
ARG VIRTUAL_ENV=/venv

ENV ENV_FILE=${ENV_FILE} \
        VIRTUAL_ENV=${VIRTUAL_ENV} 


COPY ${ENV_FILE} /conda-env.yml

RUN mamba env create -f /conda-env.yml \
    && /opt/conda/envs/airflow/bin/conda-pack --name airflow --ignore-missing-files --output /tmp/env.tar.gz \
    && mkdir -p ${VIRTUAL_ENV} \ 
    && cd ${VIRTUAL_ENV} \
    && tar -xvf /tmp/env.tar.gz \
    && rm /tmp/env.tar.gz \
    && ${VIRTUAL_ENV}/bin/conda-unpack \
    && conda clean -afy

WORKDIR ${VIRTUAL_ENV}
```


The next stage pulls from the os-dependencies image (not shown, it is just debian slim with some extra dependencies and ODBC drivers installed). It then copies the /venv directory above with all of the Python packages installed. Now I am able to have a smaller image with working packages

```
FROM os-dependencies as airflow-dev

COPY --chown=airflow:root --from=python-dependencies /venv /venv

ENV PYTHONPATH=${AIRFLOW_HOME}:$PYTHONPATH \
    PATH=${VIRTUAL_ENV}/bin:$PATH

other stuff...
```

**Comment by DeoLeung** [comment]
I could build it with below `Dockerfile`
```Dockerfile
FROM python:3.9-slim

RUN apt update && \
    apt-get install -y -V ca-certificates lsb-release wget && \
    wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb && \
    apt-get install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb && \
    apt-get update && \
    apt-get install  --no-install-recommends -y libarrow-dev g++ libboost-all-dev unixodbc-dev python3-dev

RUN pip install  --no-cache-dir  pybind11 cython pyarrow
RUN python -c "import pyarrow; pyarrow.create_library_symlinks()"
RUN apt-get install  --no-install-recommends -y odbc-postgresql
RUN pip install  --no-cache-dir turbodbc
```
now I can run `turbodbc`, but seems it cannot find pyarrow
```bash
root@c1972aa7bb7d:/# python
Python 3.9.9 (main, Nov 17 2021, 16:30:15)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from turbodbc import connect
>>> connection = connect(connection_string='Driver={PostgreSQL Unicode};Server=a;Port=b;Database=c;Uid=d;Pwd=e;')
>>> cursor = connection.cursor()
>>> cursor.execute("select * from abc")
<turbodbc.cursor.Cursor object at 0x7f2b2a462be0>
>>> table = cursor.fetchallarrow()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/turbodbc/cursor.py", line 372, in fetchallarrow
    raise Error(_NO_ARROW_SUPPORT_MSG)
turbodbc.exceptions.Error: This installation of turbodbc does not support Apache Arrow extensions. Please install the `pyarrow` package. If you have built turbodbc from source, you may also need to reinstall turbodbc to compile the extensions.
```

Do I miss something?

**Comment by ldacey** [comment]
> 
> Do I miss something?

Same issue for me when I use the create_library_symlinks() function - the installation does not have an error but pyarrow still cannot be found.

**Comment by zacqed** [comment]
This is what i do in production and it works perfectly.

Pyarrow 5.0.0

```
WORKDIR /root/.local/lib/python3.8/site-packages/pyarrow
RUN ln -s libarrow.so.500 libarrow.so
RUN ln -s libarrow_python.so.500 libarrow_python.so
RUN pip install --user turbodbc==4.2.1
```

**Comment by blackrez** [comment]
I have the same issue.
Arrow 6.0 works flawless and turbodbc install correctly with pip.

When I try to import turbodbc_ with arrow I have this error.

```
[...]
----> 1 import turbodbc_arrow_support

ImportError: /home/nabil/venv/lib/python3.8/site-packages/turbodbc_arrow_support.cpython-38-aarch64-linux-gnu.so: undefined symbol: _ZNK5arrow6Status8ToStringB5cxx11Ev
```

**Comment by enricmorales-d01** [comment]
> I have the same issue. Arrow 6.0 works flawless and turbodbc install correctly with pip.
> 
> When I try to import turbodbc_ with arrow I have this error.
> 
> ```
> [...]
> ----> 1 import turbodbc_arrow_support
> 
> ImportError: /home/nabil/venv/lib/python3.8/site-packages/turbodbc_arrow_support.cpython-38-aarch64-linux-gnu.so: undefined symbol: _ZNK5arrow6Status8ToStringB5cxx11Ev
> ```

Hello @blackrez! We are getting started with turbodbc and pyarrow and encountered the same problem. We decided to share our findings here. When trying to load the arrow support library as **root**, there was no problem there:

```
root@7aefe4977d08:/opt/airflow# python3
Python 3.8.12 (default, Dec 21 2021, 11:15:53)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import turbodbc_arrow_support
>>>
```

However, when troubleshooting this as the airflow user (the end user of the library and turbodbc), there was indeed some mismatch between libraries or whatever:

```
airflow@7aefe4977d08:/opt/airflow$ python
Python 3.8.12 (default, Dec 21 2021, 11:15:53)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import turbodbc_arrow_support
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/airflow/.local/lib/python3.8/site-packages/pyarrow/libarrow.so.700: undefined symbol: _ZTIN5arrow8DataTypeE
```

Our workaround, very quick and dirty, is to overwrite the libraries that come with the python pyarrow package so that they match the system libraries:

```
cp /usr/lib/x86_64-linux-gnu/libarrow{,_python}.so.?00 \
    /home/airflow/.local/lib/python3.8/site-packages/pyarrow
```

Here is the result:

```
airflow@airflow:~$ docker-compose exec -u airflow airflow-worker bash
airflow@7aefe4977d08:/opt/airflow$ python
Python 3.8.12 (default, Dec 21 2021, 11:15:53)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import turbodbc_arrow_support
>>>
```

**Comment by DevangB9** [comment]
@zacqed Hey, I read your suggestion, but I'm using virtual venv for my project and thus can't download it as a user. However, If I install it normally within the venv I get error while installing it. 

Any suggestions?

**Comment by DevangB9** [comment]
> I could build it with below `Dockerfile`
> 
> ```dockerfile
> FROM python:3.9-slim
> 
> RUN apt update && \
>     apt-get install -y -V ca-certificates lsb-release wget && \
>     wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb && \
>     apt-get install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb && \
>     apt-get update && \
>     apt-get install  --no-install-recommends -y libarrow-dev g++ libboost-all-dev unixodbc-dev python3-dev
> 
> RUN pip install  --no-cache-dir  pybind11 cython pyarrow
> RUN python -c "import pyarrow; pyarrow.create_library_symlinks()"
> RUN apt-get install  --no-install-recommends -y odbc-postgresql
> RUN pip install  --no-cache-dir turbodbc
> ```
> 
> now I can run `turbodbc`, but seems it cannot find pyarrow
> 
> ```shell
> root@c1972aa7bb7d:/# python
> Python 3.9.9 (main, Nov 17 2021, 16:30:15)
> [GCC 10.2.1 20210110] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from turbodbc import connect
> >>> connection = connect(connection_string='Driver={PostgreSQL Unicode};Server=a;Port=b;Database=c;Uid=d;Pwd=e;')
> >>> cursor = connection.cursor()
> >>> cursor.execute("select * from abc")
> <turbodbc.cursor.Cursor object at 0x7f2b2a462be0>
> >>> table = cursor.fetchallarrow()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.9/site-packages/turbodbc/cursor.py", line 372, in fetchallarrow
>     raise Error(_NO_ARROW_SUPPORT_MSG)
> turbodbc.exceptions.Error: This installation of turbodbc does not support Apache Arrow extensions. Please install the `pyarrow` package. If you have built turbodbc from source, you may also need to reinstall turbodbc to compile the extensions.
> ```
> 
> Do I miss something?

@DeoLeung Any luck with this?

**Comment by david-engelmann** [comment]
Has anyone made any progress on this?

**Comment by peter-wimsey** [comment]
> Has anyone made any progress on this?

No progress on turbodbc but we recently started using Arrow Flight instead.

Installation is much easier. Requests are faster but seem to consume considerably more memory. The Flight client operates on a different port and protocol so a switch will require changes to the server.

Here's example client code:

https://github.com/dremio-hub/arrow-flight-client-examples

**Comment by david-engelmann** [comment]
@peter-wimsey Arrow Flight is a great suggestion, I've considered it for my purpose as well. I've written a decent amount around turbodbc, but it seems easier at this point to make changes to the server and refactor everything than it is to install turbodbc.

**Comment by pacman82** [comment]
@david-engelmann if you should give up on turbodbc, you may not need to give up on ODBC altogether, though.  `arrow-odbc` allows you to fetch from ODBC into Arrow arrays as well. It is way more narrow in scope, but it does not rely as much on external dependencies or any C++ API/ABI, so it is easily pip installable.

<https://github.com/pacman82/arrow-odbc-py>

**Comment by david-engelmann** [comment]
For those interested in a minimal example of installing turbodbc with pyarrow support without conda, i've added an [example dockerfile setup here](https://github.com/blue-yonder/turbodbc/issues/351#issuecomment-1122946938). Hope this helps!

**Comment by ldacey** [comment]
Thanks @david-engelmann, that seemed to work for me as well. Your comment actually was a day after I began testing the arrow-odbc library that @pacman82 mentioned, but the good news is that my setup is now based on pip instead of a mix of conda + pip like it was before (due to turbodbc/pyarrow). I'll be testing Flight, arrow-odbc, and do some more testing with turbodbc to figure out what I want to move forward with.

**Comment by david-engelmann** [comment]
> Thanks @david-engelmann, that seemed to work for me as well. Your comment actually was a day after I began testing the arrow-odbc library that @pacman82 mentioned, but the good news is that my setup is now based on pip instead of a mix of conda + pip like it was before (due to turbodbc/pyarrow). I'll be testing Flight, arrow-odbc, and do some more testing with turbodbc to figure out what I want to move forward with.

I'm doing some similar benchmarking and would love to hear what you end up moving forwarded with! Turbodbc in docker helps a ton. I'm very interested in Flight but most likely sticking with Turbodbc now.
